version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sam
      POSTGRES_PASSWORD: sam
      POSTGRES_DB: sam
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
